name: Create Code And Update Next Version

# 触发器
on:
  push:
    branches:
      - rel

jobs:
  create_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PUSH_ACTION_TOKEN}}
          fetch-depth: 0
      - name: 切换到master分支
        run: |
          git checkout master
          git rebase rel
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 安装JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: 生成最新代码
        run: bash ./gradlew lib:test --tests "son.ysy.dependencies.Creator.testCreateAll"
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh lib/version.properties LIB_VERSION
      - name: 配置git
        run: bash ./sh/git_config.sh
      - name: 提交生成代码
        run: |
          git add .
          git commit -m "生成${{env.LIB_VERSION}}"
          git tag "v${{env.LIB_VERSION}}"
      - name: 更新打包版本
        run: bash ./sh/update_version.sh lib/version.properties
      - name: 更新版本环境变量
        run: bash ./sh/env_version.sh lib/version.properties LIB_NEXT_VERSION
      - name: 提交生成代码
        run: |
          git add lib/version.properties
          git commit -m "更新下次发布版本为${{env.LIB_NEXT_VERSION}}"
          git push origin master
          git push origin "v${{env.LIB_VERSION}}"
          git push origin -d rel