name: Create Code

# 触发器
on:
  push:
    branches:
      - create

jobs:
  create_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PUSH_ACTION_TOKEN}}
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 安装JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: 生成最新代码
        run: bash ./gradlew lib:test --tests "son.ysy.dependencies.Creator.testCreateAll"
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh lib/version.properties LIB_VERSION
      - name: 配置git
        run: bash ./sh/git_config.sh
      - name: 提交生成代码
        run: |
          git add .
          git commit -m "生成${{env.LIB_VERSION}}"
          git push origin create:rel
          git push origin -d create
