name: Release

# 触发器
on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh lib/version.properties LIB_VERSION
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.LIB_VERSION}}
          release_name: Release ${{env.LIB_VERSION}}
          draft: false
          prerelease: false
      - name: 删除旧tag
        run: git push origin -d ${{github.ref}}