name: Create And Release

# 触发器
on:
  push:
    branches:
      - rel

jobs:
  create_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 安装JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh lib/version.properties LIB_VERSION
      - name: 生成最新代码
        run: bash ./gradlew lib:test --tests "son.ysy.dependencies.Creator.testCreateAll"
      - name: 提交生成结果记录
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: "."
          author_name: "YCX-Github"
          author_email: "ycx974577817@gmail.com"
          message: "生成${{env.LIB_VERSION}}"
          tag: ${{env.LIB_VERSION}}
          push: true
  release:
    needs:
      - create_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: rel
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh lib/version.properties LIB_VERSION
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.LIB_VERSION}}
          release_name: Release ${{env.LIB_VERSION}}
          draft: false
          prerelease: false
  update_next_version:
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: rel
      - uses: actions/checkout@v2
        with:
          repository: qiushui95/GithubActionShell
          path: "sh"
      - name: 更新打包版本
        run: bash ./sh/update_version.sh lib/version.properties

      - name: 设置版本环境变量
        run: bash ./sh/env_version.sh lib/version.properties LIB_VERSION
      - name: 提交版本修改记录
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: "."
          author_name: "YCX-Github"
          author_email: "ycx974577817@gmail.com"
          message: "更新下次发布版本为${{env.LIB_VERSION}}"
          push: "origin rel:master -f"
